import Head from "next/head";
import Login from "./login";

export default function Home() {
  return (
    <>
      <Head>
        <title> Next </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="Generated by DK" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login />
    </>
  );
}
